### ISSUE TITLE
Passing Parameters

### ISSUE THREAD

**Issue by BillyBarbaro** [LIBOL/SOL#5]
The wiki provides the example query:
`sol_train -a ogd --params "eta=0.001;" data/a1a test.model`

However, running this results in the following error:
`sol_train: error: too few arguments`

But it does work when I add an equal sign like this:
`sol_train -a ogd --params="eta=0.001;" data/a1a test.model`

**Comment by yuewu001** [comment]
are u using python wrappers? The example is for c++ executable. Python wrapper has similar argumetns but with a litter difference. The reason for your case is that "--params" accept multiple parameter arguments.  the data path is wrongly regarded as a parameter. Some alternative parameter settings are:
    sol_train data/a1a test.model -a ogd --params "eta=0.001"
    sol_train --params "eta=0.001" -a ogd data/a1a test.model
    sol_train -a ogd --params="eta=0.001" data/a1a test.model
